# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestUI
  pod 'Alamofire'
  target 'TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestUIUITests' do
    # Pods for testing
  end

end
